package contract

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"regexp"
	"sort"
	"strings"
)

const LockSchema = "sealed-lab-image-lock/v1"
const RuntimeLockSchema = "sealed-lab-runtime-lock/v1"

var (
	digestReference = regexp.MustCompile(`^[^\s]+@sha256:[0-9a-f]{64}$`)
	sha256Value     = regexp.MustCompile(`^[0-9a-f]{64}$`)
	exactVersion    = regexp.MustCompile(`^[0-9]+\.[0-9]+\.[0-9]+(?:[-+][0-9A-Za-z.-]+)?$`)
	runtimeRunID    = regexp.MustCompile(`^[a-z0-9][a-z0-9-]{0,47}$`)
)

type Lock struct {
	Schema      string       `json:"schema"`
	Images      []Image      `json:"images"`
	CLIPackages []CLIPackage `json:"cli_packages"`
}

type Image struct {
	ID        string   `json:"id"`
	Reference string   `json:"reference"`
	Platforms []string `json:"platforms"`
}

type CLIPackage struct {
	ID        string `json:"id"`
	Package   string `json:"package"`
	Version   string `json:"version"`
	Tarball   string `json:"tarball"`
	Integrity string `json:"integrity"`
	Role      string `json:"role"`
}

type bootstrapModel struct {
	BaseModel                       string   `json:"base_model"`
	Provider                        string   `json:"provider"`
	Mode                            string   `json:"mode"`
	InputCostPerToken               *float64 `json:"input_cost_per_token"`
	OutputCostPerToken              *float64 `json:"output_cost_per_token"`
	MaxInputTokens                  int      `json:"max_input_tokens"`
	MaxOutputTokens                 int      `json:"max_output_tokens"`
	SupportsFunctionCalling         bool     `json:"supports_function_calling,omitempty"`
	SupportsParallelFunctionCalling bool     `json:"supports_parallel_function_calling,omitempty"`
	SupportsResponseSchema          bool     `json:"supports_response_schema,omitempty"`
	SupportsToolChoice              bool     `json:"supports_tool_choice,omitempty"`
}

// RuntimeLock binds locally produced artifacts to immutable OCI indexes before
// Compose interpolation. It is generated by the isolated build stage and is
// deliberately not committed with placeholder or floating references.
type RuntimeLock struct {
	Schema           string         `json:"schema"`
	RunID            string         `json:"run_id"`
	SourceLockSHA256 string         `json:"source_lock_sha256"`
	Images           []RuntimeImage `json:"images"`
}

type RuntimeImage struct {
	ID            string   `json:"id"`
	Reference     string   `json:"reference"`
	Platforms     []string `json:"platforms"`
	Source        string   `json:"source"`
	ClientVersion string   `json:"client_version,omitempty"`
}

func DecodeRuntimeLock(reader io.Reader) (*RuntimeLock, error) {
	decoder := json.NewDecoder(io.LimitReader(reader, 1<<20))
	decoder.DisallowUnknownFields()
	var lock RuntimeLock
	if err := decoder.Decode(&lock); err != nil {
		return nil, err
	}
	if err := decoder.Decode(&struct{}{}); err != io.EOF {
		return nil, fmt.Errorf("runtime lock contains trailing JSON")
	}
	if err := lock.Validate(); err != nil {
		return nil, err
	}
	return &lock, nil
}

func (lock RuntimeLock) Validate() error {
	if lock.Schema != RuntimeLockSchema || !runtimeRunID.MatchString(lock.RunID) || !sha256Value.MatchString(lock.SourceLockSHA256) || len(lock.Images) != 4 {
		return fmt.Errorf("incomplete %s lock", RuntimeLockSchema)
	}
	want := []string{"bifrost", "claude-runner", "codex-runner", "egress-sentinel"}
	for index, image := range lock.Images {
		if image.ID != want[index] || !digestReference.MatchString(image.Reference) || image.Source == "" {
			return fmt.Errorf("runtime image %q is incomplete or not digest pinned", image.ID)
		}
		if len(image.Platforms) != 2 || !sort.StringsAreSorted(image.Platforms) || image.Platforms[0] != "linux/amd64" || image.Platforms[1] != "linux/arm64" {
			return fmt.Errorf("runtime image %q lacks the native amd64/arm64 matrix", image.ID)
		}
		isRunner := image.ID == "claude-runner" || image.ID == "codex-runner"
		if isRunner != exactVersion.MatchString(image.ClientVersion) {
			return fmt.Errorf("runtime image %q has invalid client version binding", image.ID)
		}
	}
	return nil
}

func (lock RuntimeLock) ComposeEnvironment() map[string]string {
	keys := map[string]string{
		"bifrost":         "BIFROST_IMAGE",
		"claude-runner":   "CLAUDE_RUNNER_IMAGE",
		"codex-runner":    "CODEX_RUNNER_IMAGE",
		"egress-sentinel": "EGRESS_SENTINEL_IMAGE",
	}
	environment := make(map[string]string, len(lock.Images))
	for _, image := range lock.Images {
		environment[keys[image.ID]] = image.Reference
	}
	return environment
}

func SHA256Hex(data []byte) string {
	digest := sha256.Sum256(data)
	return hex.EncodeToString(digest[:])
}

func DecodeLock(reader io.Reader) (*Lock, error) {
	decoder := json.NewDecoder(io.LimitReader(reader, 1<<20))
	decoder.DisallowUnknownFields()
	var lock Lock
	if err := decoder.Decode(&lock); err != nil {
		return nil, err
	}
	if err := decoder.Decode(&struct{}{}); err != io.EOF {
		return nil, fmt.Errorf("image lock contains trailing JSON")
	}
	if err := lock.Validate(); err != nil {
		return nil, err
	}
	return &lock, nil
}

func (lock Lock) Validate() error {
	if lock.Schema != LockSchema || len(lock.Images) < 4 || len(lock.CLIPackages) != 2 {
		return fmt.Errorf("incomplete %s lock", LockSchema)
	}
	for index, image := range lock.Images {
		if image.ID == "" || !digestReference.MatchString(image.Reference) {
			return fmt.Errorf("image %q is not digest pinned", image.ID)
		}
		if index > 0 && lock.Images[index-1].ID >= image.ID {
			return fmt.Errorf("images must be sorted by unique id")
		}
		if len(image.Platforms) != 2 || !sort.StringsAreSorted(image.Platforms) || image.Platforms[0] != "linux/amd64" || image.Platforms[1] != "linux/arm64" {
			return fmt.Errorf("image %q lacks the native amd64/arm64 matrix", image.ID)
		}
	}
	for index, cli := range lock.CLIPackages {
		if cli.ID == "" || cli.Package == "" || !exactVersion.MatchString(cli.Version) || !strings.HasPrefix(cli.Tarball, "https://registry.npmjs.org/") || !strings.HasPrefix(cli.Integrity, "sha512-") || cli.Role == "" {
			return fmt.Errorf("CLI package %q is incomplete or floating", cli.ID)
		}
		if index > 0 && lock.CLIPackages[index-1].ID >= cli.ID {
			return fmt.Errorf("CLI packages must be sorted by unique id")
		}
		if !strings.Contains(cli.Tarball, cli.Version) {
			return fmt.Errorf("CLI package %q tarball does not bind its version", cli.ID)
		}
	}
	return nil
}

func ValidateCompose(data []byte) error {
	if len(data) == 0 || len(data) > 1<<20 || bytes.IndexByte(data, 0) >= 0 {
		return fmt.Errorf("invalid compose input")
	}
	lower := strings.ToLower(string(data))
	for _, forbidden := range []string{
		"localstack", "ollama", "latest", "network_mode: host", "privileged: true",
		"/var/run/docker.sock", "docker.sock", "ports:", "external: true", "restart: always", "restart: unless-stopped",
		"aws_access_key_id", "aws_secret_access_key", "aws_session_token", "http_proxy", "https_proxy",
	} {
		if strings.Contains(lower, forbidden) {
			return fmt.Errorf("compose contains forbidden token %q", forbidden)
		}
	}
	for _, required := range []string{
		"bifrost-1:", "bifrost-2:", "bifrost-3:", "postgres:", "health-stub:", "codex-runner:", "claude-runner:",
		"controlled-dns:", "egress-sentinel:", "sealed_dns_corefile:", "file: ./dns/corefile",
		"network-probe:", "sealed_network_probe:", "file: ./probe/network-negatives.sh", "target: /probe/network-negatives.sh",
		"codex_version_scenario:", "claude_version_scenario:", "target: /scenario/scenario.json",
		"frankengate_pricing_url: file:///lab-fixtures/pricing.json", "frankengate_model_parameters_url: file:///lab-fixtures/model-parameters.json",
		"sealed_pricing_fixture:", "sealed_model_parameters_fixture:",
		"netns-bifrost-1:", "netns-bifrost-2:", "netns-bifrost-3:", "netns-codex:", "netns-claude:",
		"client_net:", "data_net:", "control_net:", "internal: true", "enable_ipv6: true",
		"read_only: true", "cap_drop: [all]", "no-new-privileges:true", "pids_limit:", "tmpfs:",
		"cap_add: [net_admin]", "ip route | awk '$$1 == \"default\"'", "ip -6 route | awk '$$1 == \"default\"'", "ip route get", "network_mode: service:netns-codex", "network_mode: service:netns-claude",
		"cap_add: [net_bind_service]", "user: \"70:70\"", "/var/run/postgresql:rw,nosuid,nodev,noexec,size=4m,uid=70,gid=70",
		"dns: [\"${lab_dns_ipv4", "${lab_dns_ipv6", "dns_opt: [attempts:1, timeout:1]", "lab_sentinel_ipv4", "lab_sentinel_ipv6",
		"lab_client_ipv4_subnet", "lab_client_ipv6_subnet", "lab_data_ipv4_subnet", "lab_data_ipv6_subnet",
		"lab_control_ipv4_subnet", "lab_control_ipv6_subnet", "172.30.10.254", "fd00:bf:10::fe",
		"lab_bifrost_1_client_ipv4", "lab_bifrost_1_data_ipv4", "lab_bifrost_2_client_ipv4", "lab_bifrost_2_data_ipv4", "lab_bifrost_3_client_ipv4", "lab_bifrost_3_data_ipv4", "lab_health_ipv4",
		"${bifrost_image:?", "${codex_runner_image:?", "${claude_runner_image:?", "${egress_sentinel_image:?",
	} {
		if !strings.Contains(lower, required) {
			return fmt.Errorf("compose misses required sealed-lab contract %q", required)
		}
	}
	if strings.Count(lower, "internal: true") != 3 || strings.Count(lower, "enable_ipv6: true") != 3 {
		return fmt.Errorf("all three lab networks must be internal and dual-stack")
	}
	if strings.Count(lower, "ip route | awk '$$1 == \"default\"'") != 2 {
		return fmt.Errorf("namespace startup and health checks must preserve the IPv4 default-route contract")
	}
	for _, service := range []string{"controlled-dns", "egress-sentinel", "network-probe"} {
		if !strings.Contains(lower, "\n  "+service+":\n") {
			return fmt.Errorf("compose misses top-level service %q", service)
		}
	}
	return nil
}

// ValidateComposeAgainstLock prevents the committed topology from drifting away
// from the independently reviewed image lock. Build-produced images remain
// mandatory digest-valued environment inputs and are checked at runtime.
func ValidateComposeAgainstLock(data []byte, lock Lock) error {
	if err := ValidateCompose(data); err != nil {
		return err
	}
	text := string(data)
	required := map[string]bool{
		"alpine-netns": false,
		"coredns":      false,
		"health-stub":  false,
		"postgres":     false,
	}
	for _, image := range lock.Images {
		if _, ok := required[image.ID]; !ok {
			continue
		}
		if !strings.Contains(text, image.Reference) {
			return fmt.Errorf("compose does not use locked %s image %q", image.ID, image.Reference)
		}
		required[image.ID] = true
	}
	for id, present := range required {
		if !present {
			return fmt.Errorf("image lock lacks required compose image %q", id)
		}
	}
	return nil
}

func ValidateDNSCorefile(data []byte) error {
	if len(data) == 0 || len(data) > 64<<10 || bytes.IndexByte(data, 0) >= 0 {
		return fmt.Errorf("invalid DNS policy input")
	}
	lower := strings.ToLower(string(data))
	for _, forbidden := range []string{"forward ", "proxy ", "tls://", "fallthrough"} {
		if strings.Contains(lower, forbidden) {
			return fmt.Errorf("DNS policy contains escape path %q", forbidden)
		}
	}
	for _, required := range []string{
		".:53", "hosts {",
		"{$lab_bifrost_1_client_ipv4} bifrost-1", "{$lab_bifrost_1_client_ipv6} bifrost-1",
		"{$lab_bifrost_2_client_ipv4} bifrost-2", "{$lab_bifrost_2_client_ipv6} bifrost-2",
		"{$lab_bifrost_3_client_ipv4} bifrost-3", "{$lab_bifrost_3_client_ipv6} bifrost-3",
		"{$lab_health_ipv4} health-stub", "{$lab_health_ipv6} health-stub",
		"{$lab_sentinel_ipv4} api.anthropic.com", "{$lab_sentinel_ipv6} api.anthropic.com",
	} {
		if !strings.Contains(lower, required) {
			return fmt.Errorf("DNS policy misses %q", required)
		}
	}
	for _, dualStackTrap := range []string{
		"api.anthropic.com", "api.openai.com", "bedrock-mantle.us-east-1.api.aws",
		"metadata.google.internal", "registry.npmjs.org",
		"sentry.io", "statsig.anthropic.com",
	} {
		if strings.Count(lower, dualStackTrap) != 2 {
			return fmt.Errorf("DNS policy must trap %q on exactly two address-family rows", dualStackTrap)
		}
	}
	return nil
}

func ValidateBootstrapFixture(data []byte, requireCapabilities bool) error {
	decoder := json.NewDecoder(io.LimitReader(bytes.NewReader(data), 1<<20))
	decoder.DisallowUnknownFields()
	models := map[string]bootstrapModel{}
	if err := decoder.Decode(&models); err != nil {
		return fmt.Errorf("decode bootstrap fixture: %w", err)
	}
	if err := decoder.Decode(&struct{}{}); err != io.EOF {
		return fmt.Errorf("bootstrap fixture contains trailing JSON")
	}
	if len(models) != 1 {
		return fmt.Errorf("bootstrap fixture must contain exactly one synthetic model")
	}
	model, ok := models["openai.gpt-5.6-sol"]
	if !ok || model.BaseModel != "openai.gpt-5.6-sol" || model.Provider != "bedrock_mantle" || model.Mode != "responses" {
		return fmt.Errorf("bootstrap fixture identity drift")
	}
	if model.InputCostPerToken == nil || model.OutputCostPerToken == nil || *model.InputCostPerToken != 0 || *model.OutputCostPerToken != 0 {
		return fmt.Errorf("bootstrap fixture must remain explicitly zero-cost")
	}
	if model.MaxInputTokens <= 0 || model.MaxOutputTokens <= 0 {
		return fmt.Errorf("bootstrap fixture has invalid token bounds")
	}
	if requireCapabilities && (!model.SupportsFunctionCalling || !model.SupportsParallelFunctionCalling || !model.SupportsResponseSchema || !model.SupportsToolChoice) {
		return fmt.Errorf("model-parameter fixture lacks required Responses capabilities")
	}
	return nil
}
